# Generated by Django 4.0.4 on 2022-04-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manufactirer",
            new_name="Manufacturer",
        ),
    ]
